# Generated by Django 3.2.10 on 2023-05-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_well_number', models.CharField(max_length=20, unique=True)),
                ('oil_production', models.FloatField()),
                ('gas_production', models.FloatField()),
                ('brine_production', models.FloatField()),
            ],
        ),
    ]
